### PR TITLE
drmt_grants: make functions to streamline work

### PR DESCRIPTION
**Pull request by amandaha8**
Currently, TIRCP work is on hold. I am waiting for more data that will come from the TIRCP team, their feedback on the reports I helped automate, and the finalized data source before continuing deeper cleaning/analysis.

In the meantime, I began making functions of the code chunks that are repeated across my notebooks into a script that are repeated throughout my notebook & will continue doing so. 

- [TIRCP_functions.py](https://github.com/cal-itp/data-analyses/blob/drmt_tircp_grants/drmt_grants/TIRCP_functions.py)

This PR addresses issue:

https://github.com/cal-itp/data-infra/issues/898

### CODE REVIEW

**Comment by tiffanychu90** [comment]
Can you make these tweaks for readability:

* Remove  `pd.set_option('display.max_columns', None)` and the like in scripts. It's no longer a notebook, so you won't be displaying dfs, unless you print them in the logs, but those will only show up in the terminal
* [make replacements across multiple columns more readable](https://github.com/cal-itp/data-analyses/blob/65e486658142096dc8d4417d5dd59fcff1735af4/drmt_grants/TIRCP_functions.py#L27) with
```
cols = ["col1", "col2"]
df[cols] = df[cols].fillna(value=0)
```
* do you need [both? keep the one you need and get rid of extraneous one](https://github.com/cal-itp/data-analyses/blob/65e486658142096dc8d4417d5dd59fcff1735af4/drmt_grants/TIRCP_functions.py#L20-L23)
* this section looks like it's [missing an indent](https://github.com/cal-itp/data-analyses/blob/65e486658142096dc8d4417d5dd59fcff1735af4/drmt_grants/TIRCP_functions.py#L20-L23)
* all the lines running off the screen width, use parentheses to bring in multiple lines

**Comment by amandaha8** [comment]
@tiffanychu90 Yes I can definitely make these tweaks, could you elaborate on "all the lines running off the screen width, use parentheses to bring in multiple lines"? I don't really know how to fix this with parentheses. Thanks!

**Comment by tiffanychu90** [comment]
Ahh yes, so 2 examples, there may be a couple more: [here](https://github.com/cal-itp/data-analyses/blob/drmt_tircp_grants/drmt_grants/TIRCP_functions.py#L47) and [here](https://github.com/cal-itp/data-analyses/blob/drmt_tircp_grants/drmt_grants/TIRCP_functions.py#L101)

As one long line of code, others would scroll across to read it all
```
df[i] = df[i].replace('/', '-', regex = True).replace('Complete', '', regex = True).replace('\n', '', regex=True).replace('Pending','TBD',regex= True).fillna('TBD')
```

Generally, when there are brackets [ ], parentheses ( ), or curly brackets { }, you can have it be a new line. You can do "enter" and then indent again. This just makes it more readable because it's a chunk instead of 1 long line. The exception to this is within a print statement. 
```
df[i] = (df[i].replace('/', '-', regex = True).replace('Complete', '', regex = True)
            .replace('\n', '', regex=True).replace('Pending','TBD',regex= True)
            .fillna('TBD')
)

# Even strings can benefit from this:
URL = ("https://www.github.com/cal-itp/data-analyses/"
            "drmt/this-is-my-notebook.ipynb"
)

# But print statements, while there is a parentheses, is the exception
print(f"I want to write a long comment, followed by some code: {len(df[(df.col==1) & (df.col2 == 'something')])}")

# to shorten, you need other ways to make it readable
subset_df = df[(df.col==1) & (df.col2 == 'something')]
print(f"I want to write a long comment, followed by some code: {len(subset_df)}")

```

**Comment by amandaha8** [comment]
I just made the edits you gave me!

**Comment by tiffanychu90** [comment]
I think there's too many [indents](https://github.com/cal-itp/data-analyses/blob/a022e2673212683204a2e0604225eb0cc8d046ba/drmt_grants/TIRCP_functions.py#L137-L145) here? 

Looks good! Merge it when you're ready

**Comment by amandaha8** [comment]
> I think there's too many [indents](https://github.com/cal-itp/data-analyses/blob/a022e2673212683204a2e0604225eb0cc8d046ba/drmt_grants/TIRCP_functions.py#L137-L145) here?
> 
> Looks good! Merge it when you're ready

Thanks for flagging it, I'll check it now!

**Pull request merged**
