### PR TITLE
Aug hqta

### PR DESCRIPTION
**Pull request by tiffanychu90**
### HQTA

* **Fix**: `hqta_areas` takes in dissolved `hq_corridor_bus` before drawing new buffer around it. Dissolve to `calitp_itp_id-route_id` level.
* Save extra intermediate outputs in GCS from `C4_create_bus_hqta_types`, so building final outputs is faster 
* Add in `compile_operator_data.py` to take in compiling / caching functions that was in `traffic_ops/prep_data`
* Add in `route_id` to both `hqta_points` and `hqta_areas`
* `shared_utils.utils`: add a `geojson_gcs_export` function and take `geojson` or `geojsonl`
* Add exports to `geojson` and `geojsonl` too
* Add notebook checks to do some map sanity checks: `check1_downloads`, `check2_hq_corridors`, `check3_hqta_points`

### Traffic Ops
* Move workflow of compiling all the operator files to HQTA, since HQTA needs it for adding `route_id` info to `stop_id` (requires `trips` and `stop_times` as intermediary tables)
* Run Aug for `ca_transit_stops` and `ca_transit_routes` -- put this into enterprise geodatabase to see how metadata update goes 

Epic: #321 
GH issue: #398 , make sure this update makes it for #399

### CODE REVIEW

**Comment by tiffanychu90** [comment]
@edasmalchi: For HQTA areas, do you want the `hqta_type == hq_corridor_bus` to be dissolved by `calitp_itp_id-route_id`? `route_id` isn't kept in the final export, multiple rows would be present for the same attributes (`itp_id`, `hqta_type`, `hqta_details`), but different geometries. Would this be confusing? 

If it's too unwieldy to have only 1 dissolved area for each operator, then maybe adding back `route_id` for all the other `hqta_types` would be useful too?

This is a non-issue for HQTA points, since the `stop_id` is present to distinguish between multiple rows.

**Comment by edasmalchi** [comment]
I think it would be ideal to have a bit more granularity than the operator level. Agree that it could get confusing to have identical-seeming rows with different geometries.

So maybe adding back `route_id` for all the other `hqta_types` is the way to go?

**Comment by tiffanychu90** [comment]
@edasmalchi: Can you check the `hqta_points` and `hqta_areas` files? Added `route_id` for both files, since there's `stop_id`. Would rather not have any nulls or else it's extra confusing.

I opted not to add the `route_name` since that should be available in the `ca_transit_routes` also in the open data portal, and that's the one that's pulling a standardized name `route_name` (same as what's published in the portfolio)

```
import geopandas as gpd
from utilities import GCS_FILE_PATH

points = gpd.read_parquet(f"{GCS_FILE_PATH}hqta_points.parquet")
areas = gpd.read_parquet(f"{GCS_FILE_PATH}hqta_areas.parquet")
```

**Comment by edasmalchi** [comment]
@tiffanychu90 These look good to me!

One small thing, we seem to have calculated hqtas for a small part of Yuma, AZ. Should we go ahead and clip to CA at some point in the process?

yuma

**Comment by tiffanychu90** [comment]
For Yuma (ITP ID 386):
* HQTA points: `gpd.sjoin` with `predicate="within"` vs `predicate="intersects"` doesn't get rid of it for points 
* HQTA polygons. `predicate="within"` would filter out Yuma

After discussing, would rather have consistency between the HQTA points and polygons datasets. All points should get buffered and show up in the polygons dataset.

**Pull request merged**
