### PR TITLE
Update geog utils

### PR DESCRIPTION
**Pull request by tiffanychu90**
Updating `geography_utils` now that `dim_shapes` table exists. Work [Laurie's function](https://github.com/cal-itp/data-analyses/blob/752eb5639771cb2cd5f072f70a06effd232f5f22/gtfs_shapes_geo_examples/example_shapes_geo_handling.ipynb) into `geog_utils`

[GH issue](https://github.com/cal-itp/data-infra/issues/1210)

### CODE REVIEW

**Comment by tiffanychu90** [comment]
@edasmalchi @lauriemerrell: [takes about 11 min for all operators...much much faster!](https://github.com/cal-itp/data-analyses/blob/f9a1ddeb8cbb49a6403dd85fadf86993d060491c/bus_service_increase/test-dim-shapes.ipynb)

**Comment by lauriemerrell** [comment]
@tiffanychu90 that is great! However please be aware of #1266 - I am working on it now

**Comment by lauriemerrell** [comment]
Also, Michael did reply to our siuba question: https://github.com/machow/siuba/issues/407 -- I poked around a little earlier and I was still hitting an error, planning to investigate a bit more this week as time permits

**Comment by tiffanychu90** [comment]
@charlie-costanzo: Not sure why the `precommit` is failing, the files all passed?

**Pull request merged**
