### PR TITLE
Analytics portfolio pipeline MVP

### PR DESCRIPTION
**Pull request by atvaccaro**
## Summary

This PR adds an MVP workflow for deploying parameterized notebooks to a static site via papermill, Jupyter Book, and netlify.

A live demo site is available at https://data-analyses-test--cal-itp-previews.netlify.app and will be updated as more notebooks are tested. RT speed delay maps will be the best stress test for this pipeline.

## Features
1. YAML-configured script to parameterize notebooks, copy them into the proper docs location, and build the site with `jb`.
2. Automatic hiding of input cells so we can produce clean webpages (i.e. `hide-input` by default).
3. I've tested altair, plotly, and bokeh which are all described as playing nicely in the [Jupyter Book docs](https://jupyterbook.org/interactive/interactive.html).

## Caveats
1. Sphinx (and therefore Jupyter Book) does not play nicely with Markdown headers in `display(Markdown(...))` calls; instead, we can parameterize via a custom papermill engine.
2. I've gone down a couple rabbit holes with ipywidgets and while they will render and somewhat work with Javascript links, my broad conclusion is that we can't leverage `@interact` calls without a running kernel. Based on discussion with @tiffanychu90, we think this is an acceptable tradeoff.

### CODE REVIEW

**Comment by tiffanychu90** [comment]
Looks good @atvaccaro!

**Comment by tiffanychu90** [comment]
[original GH issue](https://github.com/cal-itp/data-infra/issues/1003)

**Comment by themightychris** [comment]
@atvaccaro should `docs/dla/e76_obligated_funds/prototype-district__district_4.ipynb` and `docs/dla/e76_obligated_funds/prototype-district__district_7.ipynb` be included in this PR? Aren't those generated files now?

**Comment by atvaccaro** [comment]
> @atvaccaro should `docs/dla/e76_obligated_funds/prototype-district__district_4.ipynb` and `docs/dla/e76_obligated_funds/prototype-district__district_7.ipynb` be included in this PR? Aren't those generated files now?

Those are the output of parameterized notebook executions; right now I think it's easier if we rely on committing those parameterized notebooks, otherwise we'd have to execute these in CI/CD. It saves us compute and infra overhead and also puts a human in charge of monitoring and correcting issues.

**Review by tiffanychu90 — APPROVED** [review]

**Pull request merged**
